version: "3.7"
secrets:
  db_replica_password:
    external: true
  db_password:
    external: true
  gcp_credentials:
    external: true

services:
  pg_master:
    image: mesoform/postgres-ha
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - PG_MASTER=true
      - POSTGRES_USER=testuser
      - PG_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=testdb
      - PG_REP_USER=testrep
      - PG_REP_PASSWORD_FILE=/run/secrets/db_replica_password
      - HBA_ADDRESS=10.0.0.0/8
      - STORAGE_BUCKET=gs://postgres13/wal-g
      - GCP_CREDENTIALS=/run/secrets/gcp_credentials
      - RESTORE_BACKUP=true
      - BACKUP_NAME=ab123c4d56e7-28012021
    ports:
      - "5432:5432"
    secrets:
      - source: db_replica_password
        uid: "70"
        gid: "70"
        mode: 0550
      - source: db_password
        uid: "70"
        gid: "70"
        mode: 0550
      - source: gcp_credentials
        uid: "70"
        gid: "70"
        mode: 0550
    networks:
      database:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
  pg_slave:
    image: mesoform/postgres-ha
    volumes:
      - pg_replica:/var/lib/postgresql/data
    environment:
      - PG_SLAVE=true
      - POSTGRES_USER=testuser
      - PG_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=testdb
      - PG_REP_USER=testrep
      - PG_REP_PASSWORD_FILE=/run/secrets/db_replica_password
      - PG_MASTER_HOST=pg_master  # This needs to be the swarm node private IP instead of the service name (pg_master) which resolves to the service IP
      - HBA_ADDRESS=10.0.0.0/8
    secrets:
      - source: db_replica_password
        uid: "70"
        gid: "70"
        mode: 0550
      - source: db_password
        uid: "70"
        gid: "70"
        mode: 0550
    networks:
      database:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints:
        - node.labels.type != primary

networks:
  database: {}

volumes:
  pg_data: {}
  pg_replica: {}
